import { WeaponType, WeaponConfig } from '../types';

export const WEAPON_CONFIGS: Record<WeaponType, WeaponConfig> = {
  PULSE_LASER: {
    type: 'PULSE_LASER',
    name: 'Pulse Laser',
    autoFireRate: 150,
    specialCooldown: 800,
    autoProjectileSpeed: 12,
    autoProjectileSize: 4,
    autoProjectileDamage: 15,
    autoProjectileLifetime: 100,
    specialDescription: 'Triple Shot - Fires 3 lasers in a spread',
    color: '#00BFFF',
    glowColor: '#00FFFF',
  },
  PLASMA_CANNON: {
    type: 'PLASMA_CANNON',
    name: 'Plasma Cannon',
    autoFireRate: 400,
    specialCooldown: 3000,
    autoProjectileSpeed: 8,
    autoProjectileSize: 8,
    autoProjectileDamage: 35,
    autoProjectileLifetime: 80,
    specialDescription: 'Explosive Blast - Massive AOE explosion on impact',
    color: '#FF4500',
    glowColor: '#FF8C00',
  },
  RAILGUN: {
    type: 'RAILGUN',
    name: 'Railgun',
    autoFireRate: 800,
    specialCooldown: 2000,
    autoProjectileSpeed: 20,
    autoProjectileSize: 3,
    autoProjectileDamage: 50,
    autoProjectileLifetime: 120,
    specialDescription: 'Piercing Shot - Penetrates all enemies in a line',
    color: '#9370DB',
    glowColor: '#BA55D3',
  },
  MISSILE_LAUNCHER: {
    type: 'MISSILE_LAUNCHER',
    name: 'Missile Launcher',
    autoFireRate: 600,
    specialCooldown: 2500,
    autoProjectileSpeed: 6,
    autoProjectileSize: 6,
    autoProjectileDamage: 25,
    autoProjectileLifetime: 150,
    specialDescription: 'Homing Missiles - 5 missiles that track nearest enemies',
    color: '#FFD700',
    glowColor: '#FFA500',
  },
  BEAM_WEAPON: {
    type: 'BEAM_WEAPON',
    name: 'Beam Weapon',
    autoFireRate: 50,
    specialCooldown: 4000,
    autoProjectileSpeed: 0, // Instant beam
    autoProjectileSize: 2,
    autoProjectileDamage: 8,
    autoProjectileLifetime: 3,
    specialDescription: 'Continuous Beam - Hold to fire devastating beam for 2 seconds',
    color: '#00FF00',
    glowColor: '#32CD32',
  },
  QUANTUM_DISRUPTOR: {
    type: 'QUANTUM_DISRUPTOR',
    name: 'Quantum Disruptor',
    autoFireRate: 300,
    specialCooldown: 3500,
    autoProjectileSpeed: 10,
    autoProjectileSize: 5,
    autoProjectileDamage: 20,
    autoProjectileLifetime: 90,
    specialDescription: 'Quantum Burst - Teleports projectiles around target area',
    color: '#FF00FF',
    glowColor: '#FF69B4',
  },
  MATTER_ANNIHILATOR: {
    type: 'MATTER_ANNIHILATOR',
    name: 'Matter Annihilator',
    autoFireRate: 1000,
    specialCooldown: 5000,
    autoProjectileSpeed: 5,
    autoProjectileSize: 10,
    autoProjectileDamage: 40,
    autoProjectileLifetime: 200,
    specialDescription: 'Gravity Well - Creates field that pulls enemies inward',
    color: '#8B0000',
    glowColor: '#DC143C',
  },
};

export const getRandomWeapon = (): WeaponType => {
  const weapons: WeaponType[] = [
    'PULSE_LASER',
    'PLASMA_CANNON',
    'RAILGUN',
    'MISSILE_LAUNCHER',
    'BEAM_WEAPON',
    'QUANTUM_DISRUPTOR',
    'MATTER_ANNIHILATOR',
  ];
  return weapons[Math.floor(Math.random() * weapons.length)];
};
